### ISSUE TITLE
Input k array and baryon boost 

### ISSUE THREAD

**Issue by felipeaoli** [MariaTsedrik/HMcode2020Emu#1]
When one passes the option k for the pk_nl with baryon boost, get_ functions return a list instead of the standard array. This breaks the line https://github.com/MariaTsedrik/HMcode2020Emu/blob/48dded475f96668977288512042c138d68b9eb05/HMcode2020Emu/matter_powerspectrum.py#L321

Locally, I fixed it by transforming to np.array the lists in lines 146, 218, 282. The changes in lines 146 and 218 are to uniformize the output from the trained model and the one after the interpolations with input k.

**Comment by MariaTsedrik** [comment]
Thank you so much for spotting this! In the newest version this issue is fixed.
